# ===================================================================
# 实验管理与日志 (Experiment Management & Logging)
# ===================================================================
# 核心标识符与可复现性设置
project: Test
exp_name: baselinev1
seed: 42

# 日志与监控
save_wandb: true
log_step: 50

# ===================================================================
# 硬件与性能配置 (Hardware & Performance)
# ===================================================================
# 硬件资源
devices:
  - 5
num_workers: 16

# 性能优化
precision: bf16-mixed
prefetch_queue_size: 16 # DataLoader 预取队列，与 num_workers 配合

# ===================================================================
# 数据管道 (Data Pipeline)
# ===================================================================
# 数据源与尺寸
data_path: ""
train_batch_size: 32
valid_batch_size: 32
image_size: 384

# ===================================================================
# 模型定义 (Model Definition)
# ===================================================================
# 架构与初始化 - 现在可以直接使用 tools/models/ 目录下的模型类名
model:
  model_name: test_network
  model_kwargs:
    in_channels: 3
    num_classes: 3

# ===================================================================
# 训练策略 (Training Strategy)
# ===================================================================
# 核心循环
epochs: 100
val_check: 1.0 # 每个 epoch 结束后进行验证

# 梯度与EMA
accumulate_grad_batches: 1
use_ema: true
ema_decay: 0.999

# ===================================================================
# 优化器与学习率调度 (Optimizer & LR Scheduler)
# ===================================================================
# 优化器参数
learning_rate: 0.0004
weight_decay: 0.05
gradient_clip_val: 1000000.0

# 学习率调度器参数 OneCycleLR 调度器
pct_start: 0.1

# ===================================================================
# 模型保存与恢复 (Checkpointing & Resuming)
# ===================================================================
# 状态管理
resume: null
save_checkpoint_num: 3
save_metric: valid_loss
