# General settings
exp_name: baselinev1
project: Test
seed: 42
resume: null
save_wandb: true
save_checkpoint_num: 3
config: config.yaml

# Data settings
data_path: ''
image_size: 384
num_classes: 3
in_chans: 3
num_workers: 8

# Training settings
epochs: 100
train_batch_size: 32
valid_batch_size: 32
learning_rate: 0.0004
weight_decay: 0.05
accumulate_grad_batches: 1
gradient_clip_val: 1000000.0
precision: bf16-mixed
log_step: 50
val_check: 1.0
devices: 0
save_metric: val_loss

# Model settings
model_name: resnet18d.ra2_in1k
pretrained: true
